print('#Travel Expenses Budget\n#February 16, 2023\n#CTI-110 P1HW2 - Travel Expense\n#Sapanghila,Ira Chriel\n#')
print('')
print('')

print('This program calculates and displays travel expenses')
print('')
budget = int(input('Enter Budget:'))
print('')
destination = str(input('Enter your travel destination: '))
print('')
gas = int(input('How much do you think will spend on gas? '))
print('')
accomodation = int(input('Approximately, how much will you need for accomodation/hotel? '))
print('')
food = int(input('Last, how much do you need for food? '))
print('------------Travel Expenses-----------')
print('Location: ' + destination)
print('Initial Budget: ', + budget)
print('')
print('Fuel: ', + gas)
print('Accomodation: ', + accomodation)
print('Food: ', + food)
print('')
print('Remaining Balance: ', budget - gas - accomodation - food)
input('Press ENTER to exit')


