print('#Travel Expenses Budget\n#March 1, 2023\n#CTI-110 P2HW1- Travel Expense\n#Sapanghila,Ira Chriel\n#')
print('')
print('')
print('This program calculates and displays travel expenses')
print('')
budget = float(input('Enter Budget:'))
print('')
destination = str(input('Enter your travel destination: '))
print('')
gas = float(input('How much do you think will spend on gas? '))
print('')
accomodation = float(input('Approximately, how much will you need for accomodation/hotel? '))
print('')
food = float(input('Last, how much do you need for food? '))
print('------------Travel Expenses-----------')
print('Location: ' + destination)
print(f'Initial Budget: ${budget:.1f}')
print(f'Fuel:           ${gas:.1f}')
print(f'Accomodation:   ${accomodation:.1f}')
print(f'Food:           ${food:.1f}')
print('--------------------------------------')
print('')
Remaining_balance = (budget - gas - accomodation - food)
print(f'Remaining Budget: ${Remaining_balance:.1f}')
print('')
input('Press ENTER to exit')


